import {
  SubmissionRequest,
  VaultingUpdate,
} from '../marketplace/dtos/marketplace.dto';
import { getConnection } from 'typeorm';
import { ItemType, VaultingStatus, VaultingUpdateType } from '../config/enum';

export async function clearDB() {
  const entities = getConnection().entityMetadatas;
  for (const entity of entities) {
    const repository = await getConnection().getRepository(entity.name);
    await repository.query(`DELETE FROM ${entity.tableName}`);
  }
}

export const imageBaseball =
  'iVBORw0KGgoAAAANSUhEUgAAAeYAAAHSCAIAAAC2Gv8jAAAAA3NCSVQICAjb4U/gAAAAGXRFWHRTb2Z0d2FyZQBnbm9tZS1zY3JlZW5zaG907wO/PgAABoFJREFUeJzt1EENwCAAwMAxJZDgXyMW+JEmdwr66phrfwAU/K8DALhl2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QcQD7TQQJe1Y7+AAAAABJRU5ErkJggg==';
export const imageBlackBox =
  'iVBORw0KGgoAAAANSUhEUgAAAeYAAAHSCAIAAAC2Gv8jAAAAA3NCSVQICAjb4U/gAAAAGXRFWHRTb2Z0d2FyZQBnbm9tZS1zY3JlZW5zaG907wO/PgAABoFJREFUeJzt1EENwCAAwMAxJZDgXyMW+JEmdwr66phrfwAU/K8DALhl2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QYdkAGZYNkGHZABmWDZBh2QAZlg2QcQD7TQQJe1Y7+AAAAABJRU5ErkJggg==';

export function newSubmissionRequest(
  user: string,
  sn: string,
  haveImage: boolean,
  order_uuid: string,
  haveImageFormat: boolean,
): SubmissionRequest {
  const image_base64 = haveImage ? imageBaseball : '';
  const image_rev_base64 = haveImage ? imageBlackBox : '';
  const image_format = haveImageFormat ? 'jpg' : '';
  const image_rev_format = haveImageFormat ? 'jpg' : '';
  return new SubmissionRequest({
    user: user,
    type: ItemType.card,
    grading_company: 'fake grading_company',
    serial_number: sn,
    title: 'fake title',
    description: 'fake description',
    genre: 'fake genre',
    manufacturer: 'fake manufacturer',
    year: 2001,
    order_uuid: order_uuid
      ? order_uuid
      : '00000000-0000-0000-0000-000000000123',
    overall_grade: 'fake overall_grade',
    sub_grades: 'fake sub_grades',
    autograph: 'fake autograph',
    subject: 'fake subject',
    est_value: 12300,
    image_base64: image_base64,
    image_format: image_format,
    image_rev_base64: image_rev_base64,
    image_rev_format: image_rev_format,
  });
}

export function newVaultingUpdateRequest(
  type: number,
  item_uuid: string,
): VaultingUpdate {
  var status: number;
  switch (type) {
    case VaultingUpdateType.Minted:
      status = VaultingStatus.Minted;
      break;
    case VaultingUpdateType.Burned:
      status = VaultingStatus.Withdrawn;
      break;
    default:
      throw new Error('Invalid vaulting update type');
  }
  // generate vaulting update request
  return new VaultingUpdate({
    collection: 'fake_collection',
    token_id: 1234,
    chain_id: 9999,
    item_uuid: item_uuid,
    burn_job_id: 27,
    mint_tx_hash: '0x0000000000000000000000000000000000000000',
    burn_tx_hash: '0x0000000000000000000000000000000000000000',
    type: type,
    status: status,
  });
}
